# Generated by Django 4.1.5 on 2023-02-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_tag',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
