# Generated by Django 4.1.5 on 2023-02-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_post', '0002_remove_post_id_tag_delete_posttag_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_post.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_post.tag')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='id_tag',
            field=models.ManyToManyField(through='app_post.PostTag', to='app_post.tag'),
        ),
    ]
